### ISSUE TITLE
如何改用 DeepSeek 接口

### ISSUE THREAD

**Issue by Kev1novo** [ligen131/remember-me#3]
你好，我正在运行你的项目，你的项目默认使用的是OpenAI的API接口，我想调用DeepSeek的接口，请问需要修改哪些地方。非常感谢！！！

**Comment by ligen131** [comment]
可以修改这里的配置：

https://github.com/ligen131/remember-me/blob/b01eb8304d0a45cd1940356b37274497830cd598/config-default.yml#L25-L30

举个例子，如果你需要使用 DeepSeek，可以改成这样：

```yaml
openai:
    api-token: sk-xxx # 这里改成你的 API key
    model: deepseek-chat
    proxy-url: https://api.deepseek.com/chat/completions
    time-out: 60
    prompt: 我是一名阿尔兹海默症患者，请根据以下内容，回答我提出的问题，如果在下面内容中找不到相关信息，请回答不知道：
```

如果 DeepSeek API 接口格式与 OpenAI API 不一致，可以手动改代码中这里的请求格式：

https://github.com/ligen131/remember-me/blob/b01eb8304d0a45cd1940356b37274497830cd598/shared/gpt/gpt.go#L61-L65
